import { addHours } from "date-fns";
import { fromZonedTime } from "date-fns-tz";
import { find as findTimezone } from "geo-tz";
import { roundsStub } from "~/__mocks__/stubs/roundsStub.ts";
import type { Schedule } from "~/helpers/types/Schedule.ts";
import type { ContestType } from "~/helpers/types.ts";
import type { InsertContest } from "~/server/db/schema/contests.ts";

function getSchedule(contest: InsertContest): Schedule {
  const rounds = roundsStub.filter((r) => r.competitionId === contest.competitionId);
  const timezone = findTimezone(contest.latitudeMicrodegrees / 1_000_000, contest.longitudeMicrodegrees / 1_000_000)[0];

  return {
    venues: [
      {
        id: 1,
        name: "Venueplace",
        countryIso2: contest.regionCode,
        latitudeMicrodegrees: 10,
        longitudeMicrodegrees: 10,
        timezone,
        rooms: [
          {
            id: 1,
            name: "Roomhall",
            color: "#000000",
            activities: rounds.map((r, index) => ({
              id: index + 1,
              activityCode: `${r.eventId}-r${r.roundNumber}`,
              startTime: fromZonedTime(addHours(contest.startDate, 12), timezone),
              endTime: fromZonedTime(addHours(contest.startDate, 13), timezone),
              childActivities: [],
            })),
          },
        ],
      },
    ],
  };
}

// Mapped to the final shape at the bottom
export const contestsStub: InsertContest[] = [
  // 2023
  {
    competitionId: "TestMeetupJan2023",
    name: "London Open 2023",
    type: "meetup" as ContestType,
    regionCode: "GB",
    city: "London",
    latitudeMicrodegrees: 51517418,
    longitudeMicrodegrees: -111220,
    startDate: new Date(2023, 0, 1),
    endDate: new Date(2023, 0, 1),
  },
  {
    competitionId: "TestCompJan2023",
    name: "French Championship 2023",
    type: "comp" as ContestType,
    regionCode: "FR",
    city: "Paris",
    latitudeMicrodegrees: 48855437,
    longitudeMicrodegrees: 2338448,
    startDate: new Date(2023, 0, 1),
    endDate: new Date(2023, 0, 1),
  },
  {
    competitionId: "TestMeetupFeb2023",
    name: "Warsaw February Meetup 2023",
    type: "meetup" as ContestType,
    regionCode: "PL",
    city: "Warsaw",
    latitudeMicrodegrees: 52197547,
    longitudeMicrodegrees: 20976267,
    startDate: new Date(2023, 1, 1),
    endDate: new Date(2023, 1, 1),
  },
  {
    competitionId: "TestCompFeb2023",
    name: "Manchester Cup 2023",
    type: "comp" as ContestType,
    regionCode: "GB",
    city: "Manchester",
    latitudeMicrodegrees: 53468947,
    longitudeMicrodegrees: -2242347,
    startDate: new Date(2023, 1, 1),
    endDate: new Date(2023, 1, 1),
  },
  {
    competitionId: "TestMeetupMar2023",
    name: "Meetup in Tokyo 2023",
    type: "meetup" as ContestType,
    regionCode: "JP",
    city: "Tokyo",
    latitudeMicrodegrees: 35708954,
    longitudeMicrodegrees: 139741849,
    startDate: new Date(2023, 2, 1),
    endDate: new Date(2023, 2, 1),
  },
  {
    competitionId: "TestCompMar2023",
    name: "American Open 2023",
    type: "comp" as ContestType,
    regionCode: "US",
    city: "Chicago",
    latitudeMicrodegrees: 41865304,
    longitudeMicrodegrees: -87661164,
    startDate: new Date(2023, 2, 1),
    endDate: new Date(2023, 2, 1),
  },
  // 2026
  {
    competitionId: "TestComp2026",
    name: "Canberra Contest 2026",
    type: "comp" as ContestType,
    regionCode: "AU",
    city: "Canberra",
    latitudeMicrodegrees: -35308264,
    longitudeMicrodegrees: 149118099,
    startDate: new Date(2026, 0, 1),
    endDate: new Date(2026, 0, 1),
  },
  {
    competitionId: "TestMeetupJan2026",
    name: "Meetup in Montevideo #3 2026",
    type: "meetup" as ContestType,
    regionCode: "UY",
    city: "Montevideo",
    latitudeMicrodegrees: -34861386,
    longitudeMicrodegrees: -56171389,
    startDate: new Date(2026, 0, 1),
    endDate: new Date(2026, 0, 1),
  },
  {
    competitionId: "TestMeetupFeb2026",
    name: "Cape Town Meet 2026",
    type: "meetup" as ContestType,
    regionCode: "ZA",
    city: "South Africa",
    latitudeMicrodegrees: -33951559,
    longitudeMicrodegrees: 18484356,
    startDate: new Date(2026, 1, 1),
    endDate: new Date(2026, 1, 1),
  },
  {
    competitionId: "TestMeetupMar2026",
    name: "Kazakhstan Speed Cup 2026",
    type: "meetup" as ContestType,
    regionCode: "KZ",
    city: "Astana",
    latitudeMicrodegrees: 51129757,
    longitudeMicrodegrees: 71436904,
    startDate: new Date(2026, 2, 1),
    endDate: new Date(2026, 2, 1),
  },
  {
    competitionId: "Munich30062026",
    name: "Meetup in Munich 30 June 2026",
    type: "meetup" as ContestType,
    regionCode: "DE",
    city: "Munich",
    latitudeMicrodegrees: 48147463,
    longitudeMicrodegrees: 11576106,
    startDate: new Date(2026, 5, 30),
    endDate: new Date(2026, 5, 30),
  },
  // 2028
  {
    competitionId: "TestMeetupJan2028",
    name: "Meetup in Rome 2028",
    type: "meetup" as ContestType,
    regionCode: "IT",
    city: "Rome",
    latitudeMicrodegrees: 41901265,
    longitudeMicrodegrees: 12509895,
    startDate: new Date(2028, 0, 1),
    endDate: new Date(2028, 0, 1),
  },
  {
    competitionId: "TestCompJan2028",
    name: "Romanian Nationals 2028",
    type: "comp" as ContestType,
    regionCode: "RO",
    city: "Bucharest",
    latitudeMicrodegrees: 44432157,
    longitudeMicrodegrees: 26113517,
    startDate: new Date(2028, 0, 1),
    endDate: new Date(2028, 0, 1),
  },
  {
    competitionId: "TestMeetupFeb2028",
    name: "Katowice Gathering 2028",
    type: "meetup" as ContestType,
    regionCode: "PL",
    city: "Katowice",
    latitudeMicrodegrees: 50258866,
    longitudeMicrodegrees: 19028235,
    startDate: new Date(2028, 1, 1),
    endDate: new Date(2028, 1, 1),
  },
  {
    competitionId: "TestCompFeb2028",
    name: "Berlin Open 2028",
    type: "comp" as ContestType,
    regionCode: "DE",
    city: "Berlin",
    latitudeMicrodegrees: 52506762,
    longitudeMicrodegrees: 13400025,
    startDate: new Date(2028, 1, 1),
    endDate: new Date(2028, 1, 1),
  },
  {
    competitionId: "TestMeetupMar2028",
    name: "Dublin March Meetup 2028",
    type: "meetup" as ContestType,
    regionCode: "IE",
    city: "Dublin",
    latitudeMicrodegrees: 53337738,
    longitudeMicrodegrees: -6277984,
    startDate: new Date(2028, 2, 1),
    endDate: new Date(2028, 2, 1),
  },
  {
    competitionId: "TestCompMar2028",
    name: "Canadian Tournament 2028",
    type: "comp" as ContestType,
    regionCode: "CA",
    city: "Toronto",
    latitudeMicrodegrees: 43665991,
    longitudeMicrodegrees: -79393860,
    startDate: new Date(2028, 2, 1),
    endDate: new Date(2028, 2, 1),
  },
  {
    competitionId: "TestMeetupApr2028",
    name: "Meetup in Croatia April 2028",
    type: "meetup" as ContestType,
    regionCode: "HR",
    city: "Zagreb",
    latitudeMicrodegrees: 45798291,
    longitudeMicrodegrees: 15986771,
    startDate: new Date(2028, 3, 1),
    endDate: new Date(2028, 3, 1),
  },
  {
    competitionId: "TestCompApr2028",
    name: "Mongolia Speed Contest 2028",
    type: "comp" as ContestType,
    regionCode: "MN",
    city: "Ulaanbaatar",
    latitudeMicrodegrees: 47907506,
    longitudeMicrodegrees: 106897423,
    startDate: new Date(2028, 3, 1),
    endDate: new Date(2028, 3, 1),
  },
].map((c) => ({
  ...c,
  state: "approved",
  shortName: c.name,
  venue: "Venueplace",
  address: "Address st. 123",
  startTime: c.type === "meetup" ? c.startDate : undefined,
  timezone: c.type === "meetup" ? "Europe/London" : undefined,
  organizerIds: [1],
  contact: "email@example.com",
  description: "Description",
  competitorLimit: 100,
  schedule: c.type === "meetup" ? undefined : getSchedule(c as InsertContest),
}));
