import type { InsertRegion } from "~/server/db/schema/regions.ts";

// Copied from migration 20260328201207_regions_table
export const regionsStub: InsertRegion[] = [
  { name: "Afghanistan", shortName: null, code: "AF", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Albania", shortName: null, code: "AL", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Algeria", shortName: null, code: "DZ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Andorra", shortName: null, code: "AD", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Angola", shortName: null, code: "AO", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  {
    name: "Antigua and Barbuda",
    shortName: null,
    code: "AG",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Argentina", shortName: null, code: "AR", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Armenia", shortName: null, code: "AM", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Australia", shortName: null, code: "AU", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Austria", shortName: null, code: "AT", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Azerbaijan", shortName: null, code: "AZ", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Bahamas", shortName: null, code: "BS", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Bahrain", shortName: null, code: "BH", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Bangladesh", shortName: null, code: "BD", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Barbados", shortName: null, code: "BB", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Belarus", shortName: null, code: "BY", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Belgium", shortName: null, code: "BE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Belize", shortName: null, code: "BZ", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Benin", shortName: null, code: "BJ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Bhutan", shortName: null, code: "BT", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Bolivia", shortName: null, code: "BO", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  {
    name: "Bosnia and Herzegovina",
    shortName: null,
    code: "BA",
    superRegionCode: "EUROPE",
    superRegionRecordType: "ER",
  },
  { name: "Botswana", shortName: null, code: "BW", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Brazil", shortName: null, code: "BR", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Brunei", shortName: null, code: "BN", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Bulgaria", shortName: null, code: "BG", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Burkina Faso", shortName: null, code: "BF", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Burundi", shortName: null, code: "BI", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Cabo Verde", shortName: null, code: "CV", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Cambodia", shortName: null, code: "KH", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Cameroon", shortName: null, code: "CM", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Canada", shortName: null, code: "CA", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  {
    name: "Central African Republic",
    shortName: null,
    code: "CF",
    superRegionCode: "AFRICA",
    superRegionRecordType: "AsR",
  },
  { name: "Chad", shortName: null, code: "TD", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Chile", shortName: null, code: "CL", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "China", shortName: null, code: "CN", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Colombia", shortName: null, code: "CO", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Comoros", shortName: null, code: "KM", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Costa Rica", shortName: null, code: "CR", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Côte d'Ivoire", shortName: null, code: "CI", superRegionCode: "AFRICA", superRegionRecordType: "AfR" },
  { name: "Croatia", shortName: null, code: "HR", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Cuba", shortName: null, code: "CU", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Cyprus", shortName: null, code: "CY", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Czechia", shortName: null, code: "CZ", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  {
    name: "Democratic Republic of the Congo",
    shortName: "DRC",
    code: "CD",
    superRegionCode: "AFRICA",
    superRegionRecordType: "AsR",
  },
  { name: "Denmark", shortName: null, code: "DK", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Djibouti", shortName: null, code: "DJ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Dominica", shortName: null, code: "DM", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  {
    name: "Dominican Republic",
    shortName: null,
    code: "DO",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Ecuador", shortName: null, code: "EC", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Egypt", shortName: null, code: "EG", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "El Salvador", shortName: null, code: "SV", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Equatorial Guinea", shortName: null, code: "GQ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Eritrea", shortName: null, code: "ER", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Estonia", shortName: null, code: "EE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Eswatini", shortName: null, code: "SZ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Ethiopia", shortName: null, code: "ET", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Fiji", shortName: null, code: "FJ", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Finland", shortName: null, code: "FI", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "France", shortName: null, code: "FR", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Gabon", shortName: null, code: "GA", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Gambia", shortName: null, code: "GM", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Georgia", shortName: null, code: "GE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Germany", shortName: null, code: "DE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Ghana", shortName: null, code: "GH", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Greece", shortName: null, code: "GR", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Grenada", shortName: null, code: "GD", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Guatemala", shortName: null, code: "GT", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Guinea", shortName: null, code: "GN", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Guinea Bissau", shortName: null, code: "GW", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Guyana", shortName: null, code: "GY", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Haiti", shortName: null, code: "HT", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Honduras", shortName: null, code: "HN", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Hong Kong", shortName: null, code: "HK", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Hungary", shortName: null, code: "HU", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Iceland", shortName: null, code: "IS", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "India", shortName: null, code: "IN", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Indonesia", shortName: null, code: "ID", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Iran", shortName: null, code: "IR", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Iraq", shortName: null, code: "IQ", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Ireland", shortName: null, code: "IE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Israel", shortName: null, code: "IL", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Italy", shortName: null, code: "IT", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Jamaica", shortName: null, code: "JM", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Japan", shortName: null, code: "JP", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Jordan", shortName: null, code: "JO", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Kazakhstan", shortName: null, code: "KZ", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Kenya", shortName: null, code: "KE", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Kiribati", shortName: null, code: "KI", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Kosovo", shortName: null, code: "XK", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Kuwait", shortName: null, code: "KW", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Kyrgyzstan", shortName: null, code: "KG", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Laos", shortName: null, code: "LA", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Latvia", shortName: null, code: "LV", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Lebanon", shortName: null, code: "LB", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Lesotho", shortName: null, code: "LS", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Liberia", shortName: null, code: "LR", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Libya", shortName: null, code: "LY", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Liechtenstein", shortName: null, code: "LI", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Lithuania", shortName: null, code: "LT", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Luxembourg", shortName: null, code: "LU", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Macau", shortName: null, code: "MO", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Madagascar", shortName: null, code: "MG", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Malawi", shortName: null, code: "MW", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Malaysia", shortName: null, code: "MY", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Maldives", shortName: null, code: "MV", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Mali", shortName: null, code: "ML", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Malta", shortName: null, code: "MT", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Marshall Islands", shortName: null, code: "MH", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Mauritania", shortName: null, code: "MR", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Mauritius", shortName: null, code: "MU", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Mexico", shortName: null, code: "MX", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Micronesia", shortName: null, code: "FM", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Moldova", shortName: null, code: "MD", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Monaco", shortName: null, code: "MC", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Mongolia", shortName: null, code: "MN", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Montenegro", shortName: null, code: "ME", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Morocco", shortName: null, code: "MA", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Mozambique", shortName: null, code: "MZ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Myanmar", shortName: null, code: "MM", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Namibia", shortName: null, code: "NA", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Nauru", shortName: null, code: "NR", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Nepal", shortName: null, code: "NP", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Netherlands", shortName: null, code: "NL", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "New Zealand", shortName: null, code: "NZ", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Nicaragua", shortName: null, code: "NI", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Niger", shortName: null, code: "NE", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Nigeria", shortName: null, code: "NG", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "North Korea", shortName: null, code: "KP", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "North Macedonia", shortName: null, code: "MK", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Norway", shortName: null, code: "NO", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Oman", shortName: null, code: "OM", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Pakistan", shortName: null, code: "PK", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Palau", shortName: null, code: "PW", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Palestine", shortName: null, code: "PS", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Panama", shortName: null, code: "PA", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  { name: "Papua New Guinea", shortName: null, code: "PG", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Paraguay", shortName: null, code: "PY", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Peru", shortName: null, code: "PE", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Philippines", shortName: null, code: "PH", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Poland", shortName: null, code: "PL", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Portugal", shortName: null, code: "PT", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Qatar", shortName: null, code: "QA", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  {
    name: "Republic of the Congo",
    shortName: null,
    code: "CG",
    superRegionCode: "AFRICA",
    superRegionRecordType: "AsR",
  },
  { name: "Romania", shortName: null, code: "RO", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Russia", shortName: null, code: "RU", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Rwanda", shortName: null, code: "RW", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  {
    name: "Saint Kitts and Nevis",
    shortName: null,
    code: "KN",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Saint Lucia", shortName: null, code: "LC", superRegionCode: "NORTH_AMERICA", superRegionRecordType: "NAR" },
  {
    name: "Saint Vincent and the Grenadines",
    shortName: null,
    code: "VC",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Samoa", shortName: null, code: "WS", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "San Marino", shortName: null, code: "SM", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  {
    name: "São Tomé and Príncipe",
    shortName: null,
    code: "ST",
    superRegionCode: "AFRICA",
    superRegionRecordType: "AsR",
  },
  { name: "Saudi Arabia", shortName: null, code: "SA", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Senegal", shortName: null, code: "SN", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Serbia", shortName: null, code: "RS", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Seychelles", shortName: null, code: "SC", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Sierra Leone", shortName: null, code: "SL", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Singapore", shortName: null, code: "SG", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Slovakia", shortName: null, code: "SK", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Slovenia", shortName: null, code: "SI", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Solomon Islands", shortName: null, code: "SB", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Somalia", shortName: null, code: "SO", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "South Africa", shortName: null, code: "ZA", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "South Korea", shortName: null, code: "KR", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "South Sudan", shortName: null, code: "SS", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Spain", shortName: null, code: "ES", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Sri Lanka", shortName: null, code: "LK", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Sudan", shortName: null, code: "SD", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Suriname", shortName: null, code: "SR", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Sweden", shortName: null, code: "SE", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Switzerland", shortName: null, code: "CH", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Syria", shortName: null, code: "SY", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Taiwan", shortName: null, code: "TW", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Tajikistan", shortName: null, code: "TJ", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Tanzania", shortName: null, code: "TZ", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Thailand", shortName: null, code: "TH", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Timor-Leste", shortName: null, code: "TL", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Togo", shortName: null, code: "TG", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Tonga", shortName: null, code: "TO", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  {
    name: "Trinidad and Tobago",
    shortName: null,
    code: "TT",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Tunisia", shortName: null, code: "TN", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Turkmenistan", shortName: null, code: "TM", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Tuvalu", shortName: null, code: "TV", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Türkiye", shortName: null, code: "TR", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Uganda", shortName: null, code: "UG", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Ukraine", shortName: null, code: "UA", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "United Arab Emirates", shortName: "UAE", code: "AE", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "United Kingdom", shortName: "UK", code: "GB", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  {
    name: "United States",
    shortName: "USA",
    code: "US",
    superRegionCode: "NORTH_AMERICA",
    superRegionRecordType: "NAR",
  },
  { name: "Uruguay", shortName: null, code: "UY", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Uzbekistan", shortName: null, code: "UZ", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Vanuatu", shortName: null, code: "VU", superRegionCode: "OCEANIA", superRegionRecordType: "OcR" },
  { name: "Vatican City", shortName: null, code: "VA", superRegionCode: "EUROPE", superRegionRecordType: "ER" },
  { name: "Venezuela", shortName: null, code: "VE", superRegionCode: "SOUTH_AMERICA", superRegionRecordType: "SAR" },
  { name: "Vietnam", shortName: null, code: "VN", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Yemen", shortName: null, code: "YE", superRegionCode: "ASIA", superRegionRecordType: "AsR" },
  { name: "Zambia", shortName: null, code: "ZM", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
  { name: "Zimbabwe", shortName: null, code: "ZW", superRegionCode: "AFRICA", superRegionRecordType: "AsR" },
];
