import type { InsertRegion } from "~/server/db/schema/regions.ts";

export function getDefaultRegions(organizationId: string): InsertRegion[] {
  return [
    {
      name: "Afghanistan",
      code: "AF",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Albania",
      code: "AL",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Algeria",
      code: "DZ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Andorra",
      code: "AD",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Angola",
      code: "AO",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Antigua and Barbuda",
      code: "AG",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Argentina",
      code: "AR",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Armenia",
      code: "AM",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Australia",
      code: "AU",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Austria",
      code: "AT",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Azerbaijan",
      code: "AZ",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Bahamas",
      code: "BS",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Bahrain",
      code: "BH",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Bangladesh",
      code: "BD",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Barbados",
      code: "BB",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Belarus",
      code: "BY",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Belgium",
      code: "BE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Belize",
      code: "BZ",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Benin",
      code: "BJ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Bhutan",
      code: "BT",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Bolivia",
      code: "BO",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Bosnia and Herzegovina",
      code: "BA",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Botswana",
      code: "BW",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Brazil",
      code: "BR",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Brunei",
      code: "BN",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Bulgaria",
      code: "BG",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Burkina Faso",
      code: "BF",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Burundi",
      code: "BI",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Cabo Verde",
      code: "CV",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Cambodia",
      code: "KH",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Cameroon",
      code: "CM",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Canada",
      code: "CA",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Central African Republic",
      code: "CF",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Chad",
      code: "TD",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Chile",
      code: "CL",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "China",
      code: "CN",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Colombia",
      code: "CO",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Comoros",
      code: "KM",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Costa Rica",
      code: "CR",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Côte d'Ivoire",
      code: "CI",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Croatia",
      code: "HR",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Cuba",
      code: "CU",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Cyprus",
      code: "CY",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Czechia",
      code: "CZ",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Democratic Republic of the Congo",
      shortName: "DRC",
      code: "CD",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Denmark",
      code: "DK",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Djibouti",
      code: "DJ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Dominica",
      code: "DM",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Dominican Republic",
      code: "DO",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Ecuador",
      code: "EC",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Egypt",
      code: "EG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "El Salvador",
      code: "SV",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Equatorial Guinea",
      code: "GQ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Eritrea",
      code: "ER",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Estonia",
      code: "EE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Eswatini",
      code: "SZ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Ethiopia",
      code: "ET",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Fiji",
      code: "FJ",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Finland",
      code: "FI",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "France",
      code: "FR",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Gabon",
      code: "GA",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Gambia",
      code: "GM",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Georgia",
      code: "GE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Germany",
      code: "DE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Ghana",
      code: "GH",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Greece",
      code: "GR",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Grenada",
      code: "GD",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Guatemala",
      code: "GT",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Guinea",
      code: "GN",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Guinea Bissau",
      code: "GW",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Guyana",
      code: "GY",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Haiti",
      code: "HT",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Honduras",
      code: "HN",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Hong Kong",
      code: "HK",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Hungary",
      code: "HU",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Iceland",
      code: "IS",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "India",
      code: "IN",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Indonesia",
      code: "ID",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Iran",
      code: "IR",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Iraq",
      code: "IQ",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Ireland",
      code: "IE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Israel",
      code: "IL",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Italy",
      code: "IT",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Jamaica",
      code: "JM",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Japan",
      code: "JP",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Jordan",
      code: "JO",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Kazakhstan",
      code: "KZ",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Kenya",
      code: "KE",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Kiribati",
      code: "KI",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Kosovo",
      code: "XK",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Kuwait",
      code: "KW",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Kyrgyzstan",
      code: "KG",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Laos",
      code: "LA",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Latvia",
      code: "LV",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Lebanon",
      code: "LB",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Lesotho",
      code: "LS",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Liberia",
      code: "LR",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Libya",
      code: "LY",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Liechtenstein",
      code: "LI",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Lithuania",
      code: "LT",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Luxembourg",
      code: "LU",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Macau",
      code: "MO",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Madagascar",
      code: "MG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Malawi",
      code: "MW",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Malaysia",
      code: "MY",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Maldives",
      code: "MV",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Mali",
      code: "ML",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Malta",
      code: "MT",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Marshall Islands",
      code: "MH",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Mauritania",
      code: "MR",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Mauritius",
      code: "MU",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Mexico",
      code: "MX",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Micronesia",
      code: "FM",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Moldova",
      code: "MD",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Monaco",
      code: "MC",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Mongolia",
      code: "MN",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Montenegro",
      code: "ME",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Morocco",
      code: "MA",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Mozambique",
      code: "MZ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Myanmar",
      code: "MM",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Namibia",
      code: "NA",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Nauru",
      code: "NR",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Nepal",
      code: "NP",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Netherlands",
      code: "NL",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "New Zealand",
      code: "NZ",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Nicaragua",
      code: "NI",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Niger",
      code: "NE",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Nigeria",
      code: "NG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "North Korea",
      code: "KP",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "North Macedonia",
      code: "MK",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Norway",
      code: "NO",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Oman",
      code: "OM",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Pakistan",
      code: "PK",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Palau",
      code: "PW",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Palestine",
      code: "PS",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Panama",
      code: "PA",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Papua New Guinea",
      code: "PG",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Paraguay",
      code: "PY",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Peru",
      code: "PE",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Philippines",
      code: "PH",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Poland",
      code: "PL",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Portugal",
      code: "PT",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Qatar",
      code: "QA",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Republic of the Congo",
      code: "CG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Romania",
      code: "RO",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Russia",
      code: "RU",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Rwanda",
      code: "RW",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Saint Kitts and Nevis",
      code: "KN",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Saint Lucia",
      code: "LC",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Samoa",
      code: "WS",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "San Marino",
      code: "SM",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "São Tomé and Príncipe",
      code: "ST",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Saudi Arabia",
      code: "SA",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Senegal",
      code: "SN",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Serbia",
      code: "RS",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Seychelles",
      code: "SC",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Sierra Leone",
      code: "SL",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Singapore",
      code: "SG",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Slovakia",
      code: "SK",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Slovenia",
      code: "SI",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Solomon Islands",
      code: "SB",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Somalia",
      code: "SO",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "South Africa",
      code: "ZA",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "South Korea",
      code: "KR",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "South Sudan",
      code: "SS",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Spain",
      code: "ES",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Sri Lanka",
      code: "LK",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Sudan",
      code: "SD",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Suriname",
      code: "SR",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Sweden",
      code: "SE",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Switzerland",
      code: "CH",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Syria",
      code: "SY",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Taiwan",
      code: "TW",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Tajikistan",
      code: "TJ",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Tanzania",
      code: "TZ",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Thailand",
      code: "TH",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Timor-Leste",
      code: "TL",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Togo",
      code: "TG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Tonga",
      code: "TO",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Trinidad and Tobago",
      code: "TT",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Tunisia",
      code: "TN",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Turkmenistan",
      code: "TM",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Tuvalu",
      code: "TV",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Türkiye",
      code: "TR",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Uganda",
      code: "UG",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Ukraine",
      code: "UA",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "United Arab Emirates",
      shortName: "UAE",
      code: "AE",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "United Kingdom",
      shortName: "UK",
      code: "GB",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "United States",
      shortName: "USA",
      code: "US",
      type: "country" as const,
      superRegionCode: "XN" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Uruguay",
      code: "UY",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Uzbekistan",
      code: "UZ",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Vanuatu",
      code: "VU",
      type: "country" as const,
      superRegionCode: "XO" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Vatican City",
      code: "VA",
      type: "country" as const,
      superRegionCode: "XE" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Venezuela",
      code: "VE",
      type: "country" as const,
      superRegionCode: "XS" as const,
      superRegionRecordType: "SAR" as const,
    },
    {
      name: "Vietnam",
      code: "VN",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Yemen",
      code: "YE",
      type: "country" as const,
      superRegionCode: "XA" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Zambia",
      code: "ZM",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Zimbabwe",
      code: "ZW",
      type: "country" as const,
      superRegionCode: "XF" as const,
      superRegionRecordType: "AfR" as const,
    },
    // Super-regions
    {
      name: "Multiple Countries (Asia)",
      shortName: "Asia",
      code: "XA",
      type: "super-region" as const,
      superRegionRecordType: "AsR" as const,
    },
    {
      name: "Multiple Countries (Europe)",
      shortName: "Europe",
      code: "XE",
      type: "super-region" as const,
      superRegionRecordType: "ER" as const,
    },
    {
      name: "Multiple Countries (Africa)",
      shortName: "Africa",
      code: "XF",
      type: "super-region" as const,
      superRegionRecordType: "AfR" as const,
    },
    {
      name: "Multiple Countries (Oceania)",
      shortName: "Oceania",
      code: "XO",
      type: "super-region" as const,
      superRegionRecordType: "OcR" as const,
    },
    {
      name: "Multiple Countries (North America)",
      shortName: "North America",
      code: "XN",
      type: "super-region" as const,
      superRegionRecordType: "NAR" as const,
    },
    {
      name: "Multiple Countries (South America)",
      shortName: "South America",
      code: "XS",
      type: "super-region" as const,
      superRegionRecordType: "SAR" as const,
    },
    // Meta-regions
    { name: "Multiple Countries (Americas)", shortName: "Americas", code: "XM", type: "meta-region" as const },
    { name: "Multiple Countries (World)", shortName: "World", code: "XW", type: "meta-region" as const },
  ].map((r) => ({ ...r, organizationId }));
}
