ALTER TABLE "record_ranks"."settings" DROP CONSTRAINT "settings_key_key";--> statement-breakpoint
ALTER TABLE "record_ranks"."settings" ADD CONSTRAINT "unique_settings_key" UNIQUE("organization_id","key");--> statement-breakpoint
ALTER TABLE "record_ranks"."contests" DROP CONSTRAINT "contests_organization_id_organizations_id_fkey", ADD CONSTRAINT "contests_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."events" DROP CONSTRAINT "events_organization_id_organizations_id_fkey", ADD CONSTRAINT "events_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."persons" DROP CONSTRAINT "persons_organization_id_organizations_id_fkey", ADD CONSTRAINT "persons_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."posts" DROP CONSTRAINT "posts_organization_id_organizations_id_fkey", ADD CONSTRAINT "posts_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."record_configs" DROP CONSTRAINT "record_configs_organization_id_organizations_id_fkey", ADD CONSTRAINT "record_configs_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."regions" DROP CONSTRAINT "regions_organization_id_organizations_id_fkey", ADD CONSTRAINT "regions_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."results" DROP CONSTRAINT "results_organization_id_organizations_id_fkey", ADD CONSTRAINT "results_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."rounds" DROP CONSTRAINT "rounds_organization_id_organizations_id_fkey", ADD CONSTRAINT "rounds_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."settings" DROP CONSTRAINT "settings_organization_id_organizations_id_fkey", ADD CONSTRAINT "settings_organization_id_organizations_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "record_ranks"."organizations"("id") ON DELETE CASCADE;