CREATE TYPE "record_ranks"."super_region_code" AS ENUM('AFRICA', 'ASIA', 'EUROPE', 'NORTH_AMERICA', 'OCEANIA', 'SOUTH_AMERICA');--> statement-breakpoint
CREATE TYPE "record_ranks"."super_region_record_type" AS ENUM('ER', 'NAR', 'SAR', 'AsR', 'AfR', 'OcR');--> statement-breakpoint
CREATE TABLE "record_ranks"."regions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "record_ranks"."regions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"short_name" text,
	"code" varchar(2) NOT NULL UNIQUE,
	"super_region_code" "record_ranks"."super_region_code" NOT NULL,
	"super_region_record_type" "record_ranks"."super_region_record_type" NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- CUSTOM ADDITION FOR RECORDRANKS!
INSERT INTO "record_ranks"."regions" ("name", "short_name", "code", "super_region_code", "super_region_record_type") VALUES
  ('Afghanistan', NULL, 'AF', 'ASIA', 'AsR'),
  ('Albania', NULL, 'AL', 'EUROPE', 'ER'),
  ('Algeria', NULL, 'DZ', 'AFRICA', 'AfR'),
  ('Andorra', NULL, 'AD', 'EUROPE', 'ER'),
  ('Angola', NULL, 'AO', 'AFRICA', 'AfR'),
  ('Antigua and Barbuda', NULL, 'AG', 'NORTH_AMERICA', 'NAR'),
  ('Argentina', NULL, 'AR', 'SOUTH_AMERICA', 'SAR'),
  ('Armenia', NULL, 'AM', 'EUROPE', 'ER'),
  ('Australia', NULL, 'AU', 'OCEANIA', 'OcR'),
  ('Austria', NULL, 'AT', 'EUROPE', 'ER'),
  ('Azerbaijan', NULL, 'AZ', 'EUROPE', 'ER'),
  ('Bahamas', NULL, 'BS', 'NORTH_AMERICA', 'NAR'),
  ('Bahrain', NULL, 'BH', 'ASIA', 'AsR'),
  ('Bangladesh', NULL, 'BD', 'ASIA', 'AsR'),
  ('Barbados', NULL, 'BB', 'NORTH_AMERICA', 'NAR'),
  ('Belarus', NULL, 'BY', 'EUROPE', 'ER'),
  ('Belgium', NULL, 'BE', 'EUROPE', 'ER'),
  ('Belize', NULL, 'BZ', 'NORTH_AMERICA', 'NAR'),
  ('Benin', NULL, 'BJ', 'AFRICA', 'AfR'),
  ('Bhutan', NULL, 'BT', 'ASIA', 'AsR'),
  ('Bolivia', NULL, 'BO', 'SOUTH_AMERICA', 'SAR'),
  ('Bosnia and Herzegovina', NULL, 'BA', 'EUROPE', 'ER'),
  ('Botswana', NULL, 'BW', 'AFRICA', 'AfR'),
  ('Brazil', NULL, 'BR', 'SOUTH_AMERICA', 'SAR'),
  ('Brunei', NULL, 'BN', 'ASIA', 'AsR'),
  ('Bulgaria', NULL, 'BG', 'EUROPE', 'ER'),
  ('Burkina Faso', NULL, 'BF', 'AFRICA', 'AfR'),
  ('Burundi', NULL, 'BI', 'AFRICA', 'AfR'),
  ('Cabo Verde', NULL, 'CV', 'AFRICA', 'AfR'),
  ('Cambodia', NULL, 'KH', 'ASIA', 'AsR'),
  ('Cameroon', NULL, 'CM', 'AFRICA', 'AfR'),
  ('Canada', NULL, 'CA', 'NORTH_AMERICA', 'NAR'),
  ('Central African Republic', NULL, 'CF', 'AFRICA', 'AfR'),
  ('Chad', NULL, 'TD', 'AFRICA', 'AfR'),
  ('Chile', NULL, 'CL', 'SOUTH_AMERICA', 'SAR'),
  ('China', NULL, 'CN', 'ASIA', 'AsR'),
  ('Colombia', NULL, 'CO', 'SOUTH_AMERICA', 'SAR'),
  ('Comoros', NULL, 'KM', 'AFRICA', 'AfR'),
  ('Costa Rica', NULL, 'CR', 'NORTH_AMERICA', 'NAR'),
  ('Côte d''Ivoire', NULL, 'CI', 'AFRICA', 'AfR'),
  ('Croatia', NULL, 'HR', 'EUROPE', 'ER'),
  ('Cuba', NULL, 'CU', 'NORTH_AMERICA', 'NAR'),
  ('Cyprus', NULL, 'CY', 'EUROPE', 'ER'),
  ('Czechia', NULL, 'CZ', 'EUROPE', 'ER'),
  ('Democratic Republic of the Congo', 'DRC', 'CD', 'AFRICA', 'AfR'),
  ('Denmark', NULL, 'DK', 'EUROPE', 'ER'),
  ('Djibouti', NULL, 'DJ', 'AFRICA', 'AfR'),
  ('Dominica', NULL, 'DM', 'NORTH_AMERICA', 'NAR'),
  ('Dominican Republic', NULL, 'DO', 'NORTH_AMERICA', 'NAR'),
  ('Ecuador', NULL, 'EC', 'SOUTH_AMERICA', 'SAR'),
  ('Egypt', NULL, 'EG', 'AFRICA', 'AfR'),
  ('El Salvador', NULL, 'SV', 'NORTH_AMERICA', 'NAR'),
  ('Equatorial Guinea', NULL, 'GQ', 'AFRICA', 'AfR'),
  ('Eritrea', NULL, 'ER', 'AFRICA', 'AfR'),
  ('Estonia', NULL, 'EE', 'EUROPE', 'ER'),
  ('Eswatini', NULL, 'SZ', 'AFRICA', 'AfR'),
  ('Ethiopia', NULL, 'ET', 'AFRICA', 'AfR'),
  ('Fiji', NULL, 'FJ', 'OCEANIA', 'OcR'),
  ('Finland', NULL, 'FI', 'EUROPE', 'ER'),
  ('France', NULL, 'FR', 'EUROPE', 'ER'),
  ('Gabon', NULL, 'GA', 'AFRICA', 'AfR'),
  ('Gambia', NULL, 'GM', 'AFRICA', 'AfR'),
  ('Georgia', NULL, 'GE', 'EUROPE', 'ER'),
  ('Germany', NULL, 'DE', 'EUROPE', 'ER'),
  ('Ghana', NULL, 'GH', 'AFRICA', 'AfR'),
  ('Greece', NULL, 'GR', 'EUROPE', 'ER'),
  ('Grenada', NULL, 'GD', 'NORTH_AMERICA', 'NAR'),
  ('Guatemala', NULL, 'GT', 'NORTH_AMERICA', 'NAR'),
  ('Guinea', NULL, 'GN', 'AFRICA', 'AfR'),
  ('Guinea Bissau', NULL, 'GW', 'AFRICA', 'AfR'),
  ('Guyana', NULL, 'GY', 'SOUTH_AMERICA', 'SAR'),
  ('Haiti', NULL, 'HT', 'NORTH_AMERICA', 'NAR'),
  ('Honduras', NULL, 'HN', 'NORTH_AMERICA', 'NAR'),
  ('Hong Kong', NULL, 'HK', 'ASIA', 'AsR'),
  ('Hungary', NULL, 'HU', 'EUROPE', 'ER'),
  ('Iceland', NULL, 'IS', 'EUROPE', 'ER'),
  ('India', NULL, 'IN', 'ASIA', 'AsR'),
  ('Indonesia', NULL, 'ID', 'ASIA', 'AsR'),
  ('Iran', NULL, 'IR', 'ASIA', 'AsR'),
  ('Iraq', NULL, 'IQ', 'ASIA', 'AsR'),
  ('Ireland', NULL, 'IE', 'EUROPE', 'ER'),
  ('Israel', NULL, 'IL', 'EUROPE', 'ER'),
  ('Italy', NULL, 'IT', 'EUROPE', 'ER'),
  ('Jamaica', NULL, 'JM', 'NORTH_AMERICA', 'NAR'),
  ('Japan', NULL, 'JP', 'ASIA', 'AsR'),
  ('Jordan', NULL, 'JO', 'ASIA', 'AsR'),
  ('Kazakhstan', NULL, 'KZ', 'ASIA', 'AsR'),
  ('Kenya', NULL, 'KE', 'AFRICA', 'AfR'),
  ('Kiribati', NULL, 'KI', 'OCEANIA', 'OcR'),
  ('Kosovo', NULL, 'XK', 'EUROPE', 'ER'),
  ('Kuwait', NULL, 'KW', 'ASIA', 'AsR'),
  ('Kyrgyzstan', NULL, 'KG', 'ASIA', 'AsR'),
  ('Laos', NULL, 'LA', 'ASIA', 'AsR'),
  ('Latvia', NULL, 'LV', 'EUROPE', 'ER'),
  ('Lebanon', NULL, 'LB', 'ASIA', 'AsR'),
  ('Lesotho', NULL, 'LS', 'AFRICA', 'AfR'),
  ('Liberia', NULL, 'LR', 'AFRICA', 'AfR'),
  ('Libya', NULL, 'LY', 'AFRICA', 'AfR'),
  ('Liechtenstein', NULL, 'LI', 'EUROPE', 'ER'),
  ('Lithuania', NULL, 'LT', 'EUROPE', 'ER'),
  ('Luxembourg', NULL, 'LU', 'EUROPE', 'ER'),
  ('Macau', NULL, 'MO', 'ASIA', 'AsR'),
  ('Madagascar', NULL, 'MG', 'AFRICA', 'AfR'),
  ('Malawi', NULL, 'MW', 'AFRICA', 'AfR'),
  ('Malaysia', NULL, 'MY', 'ASIA', 'AsR'),
  ('Maldives', NULL, 'MV', 'ASIA', 'AsR'),
  ('Mali', NULL, 'ML', 'AFRICA', 'AfR'),
  ('Malta', NULL, 'MT', 'EUROPE', 'ER'),
  ('Marshall Islands', NULL, 'MH', 'OCEANIA', 'OcR'),
  ('Mauritania', NULL, 'MR', 'AFRICA', 'AfR'),
  ('Mauritius', NULL, 'MU', 'AFRICA', 'AfR'),
  ('Mexico', NULL, 'MX', 'NORTH_AMERICA', 'NAR'),
  ('Micronesia', NULL, 'FM', 'OCEANIA', 'OcR'),
  ('Moldova', NULL, 'MD', 'EUROPE', 'ER'),
  ('Monaco', NULL, 'MC', 'EUROPE', 'ER'),
  ('Mongolia', NULL, 'MN', 'ASIA', 'AsR'),
  ('Montenegro', NULL, 'ME', 'EUROPE', 'ER'),
  ('Morocco', NULL, 'MA', 'AFRICA', 'AfR'),
  ('Mozambique', NULL, 'MZ', 'AFRICA', 'AfR'),
  ('Myanmar', NULL, 'MM', 'ASIA', 'AsR'),
  ('Namibia', NULL, 'NA', 'AFRICA', 'AfR'),
  ('Nauru', NULL, 'NR', 'OCEANIA', 'OcR'),
  ('Nepal', NULL, 'NP', 'ASIA', 'AsR'),
  ('Netherlands', NULL, 'NL', 'EUROPE', 'ER'),
  ('New Zealand', NULL, 'NZ', 'OCEANIA', 'OcR'),
  ('Nicaragua', NULL, 'NI', 'NORTH_AMERICA', 'NAR'),
  ('Niger', NULL, 'NE', 'AFRICA', 'AfR'),
  ('Nigeria', NULL, 'NG', 'AFRICA', 'AfR'),
  ('North Korea', NULL, 'KP', 'ASIA', 'AsR'),
  ('North Macedonia', NULL, 'MK', 'EUROPE', 'ER'),
  ('Norway', NULL, 'NO', 'EUROPE', 'ER'),
  ('Oman', NULL, 'OM', 'ASIA', 'AsR'),
  ('Pakistan', NULL, 'PK', 'ASIA', 'AsR'),
  ('Palau', NULL, 'PW', 'OCEANIA', 'OcR'),
  ('Palestine', NULL, 'PS', 'ASIA', 'AsR'),
  ('Panama', NULL, 'PA', 'NORTH_AMERICA', 'NAR'),
  ('Papua New Guinea', NULL, 'PG', 'OCEANIA', 'OcR'),
  ('Paraguay', NULL, 'PY', 'SOUTH_AMERICA', 'SAR'),
  ('Peru', NULL, 'PE', 'SOUTH_AMERICA', 'SAR'),
  ('Philippines', NULL, 'PH', 'ASIA', 'AsR'),
  ('Poland', NULL, 'PL', 'EUROPE', 'ER'),
  ('Portugal', NULL, 'PT', 'EUROPE', 'ER'),
  ('Qatar', NULL, 'QA', 'ASIA', 'AsR'),
  ('Republic of the Congo', NULL, 'CG', 'AFRICA', 'AfR'),
  ('Romania', NULL, 'RO', 'EUROPE', 'ER'),
  ('Russia', NULL, 'RU', 'EUROPE', 'ER'),
  ('Rwanda', NULL, 'RW', 'AFRICA', 'AfR'),
  ('Saint Kitts and Nevis', NULL, 'KN', 'NORTH_AMERICA', 'NAR'),
  ('Saint Lucia', NULL, 'LC', 'NORTH_AMERICA', 'NAR'),
  ('Saint Vincent and the Grenadines', NULL, 'VC', 'NORTH_AMERICA', 'NAR'),
  ('Samoa', NULL, 'WS', 'OCEANIA', 'OcR'),
  ('San Marino', NULL, 'SM', 'EUROPE', 'ER'),
  ('São Tomé and Príncipe', NULL, 'ST', 'AFRICA', 'AfR'),
  ('Saudi Arabia', NULL, 'SA', 'ASIA', 'AsR'),
  ('Senegal', NULL, 'SN', 'AFRICA', 'AfR'),
  ('Serbia', NULL, 'RS', 'EUROPE', 'ER'),
  ('Seychelles', NULL, 'SC', 'AFRICA', 'AfR'),
  ('Sierra Leone', NULL, 'SL', 'AFRICA', 'AfR'),
  ('Singapore', NULL, 'SG', 'ASIA', 'AsR'),
  ('Slovakia', NULL, 'SK', 'EUROPE', 'ER'),
  ('Slovenia', NULL, 'SI', 'EUROPE', 'ER'),
  ('Solomon Islands', NULL, 'SB', 'OCEANIA', 'OcR'),
  ('Somalia', NULL, 'SO', 'AFRICA', 'AfR'),
  ('South Africa', NULL, 'ZA', 'AFRICA', 'AfR'),
  ('South Korea', NULL, 'KR', 'ASIA', 'AsR'),
  ('South Sudan', NULL, 'SS', 'AFRICA', 'AfR'),
  ('Spain', NULL, 'ES', 'EUROPE', 'ER'),
  ('Sri Lanka', NULL, 'LK', 'ASIA', 'AsR'),
  ('Sudan', NULL, 'SD', 'AFRICA', 'AfR'),
  ('Suriname', NULL, 'SR', 'SOUTH_AMERICA', 'SAR'),
  ('Sweden', NULL, 'SE', 'EUROPE', 'ER'),
  ('Switzerland', NULL, 'CH', 'EUROPE', 'ER'),
  ('Syria', NULL, 'SY', 'ASIA', 'AsR'),
  ('Taiwan', NULL, 'TW', 'ASIA', 'AsR'),
  ('Tajikistan', NULL, 'TJ', 'ASIA', 'AsR'),
  ('Tanzania', NULL, 'TZ', 'AFRICA', 'AfR'),
  ('Thailand', NULL, 'TH', 'ASIA', 'AsR'),
  ('Timor-Leste', NULL, 'TL', 'ASIA', 'AsR'),
  ('Togo', NULL, 'TG', 'AFRICA', 'AfR'),
  ('Tonga', NULL, 'TO', 'OCEANIA', 'OcR'),
  ('Trinidad and Tobago', NULL, 'TT', 'NORTH_AMERICA', 'NAR'),
  ('Tunisia', NULL, 'TN', 'AFRICA', 'AfR'),
  ('Turkmenistan', NULL, 'TM', 'ASIA', 'AsR'),
  ('Tuvalu', NULL, 'TV', 'OCEANIA', 'OcR'),
  ('Türkiye', NULL, 'TR', 'EUROPE', 'ER'),
  ('Uganda', NULL, 'UG', 'AFRICA', 'AfR'),
  ('Ukraine', NULL, 'UA', 'EUROPE', 'ER'),
  ('United Arab Emirates', 'UAE', 'AE', 'ASIA', 'AsR'),
  ('United Kingdom', 'UK', 'GB', 'EUROPE', 'ER'),
  ('United States', 'USA', 'US', 'NORTH_AMERICA', 'NAR'),
  ('Uruguay', NULL, 'UY', 'SOUTH_AMERICA', 'SAR'),
  ('Uzbekistan', NULL, 'UZ', 'ASIA', 'AsR'),
  ('Vanuatu', NULL, 'VU', 'OCEANIA', 'OcR'),
  ('Vatican City', NULL, 'VA', 'EUROPE', 'ER'),
  ('Venezuela', NULL, 'VE', 'SOUTH_AMERICA', 'SAR'),
  ('Vietnam', NULL, 'VN', 'ASIA', 'AsR'),
  ('Yemen', NULL, 'YE', 'ASIA', 'AsR'),
  ('Zambia', NULL, 'ZM', 'AFRICA', 'AfR'),
  ('Zimbabwe', NULL, 'ZW', 'AFRICA', 'AfR');
--> statement-breakpoint
ALTER TABLE "record_ranks"."contests" ALTER COLUMN "region_code" SET DATA TYPE varchar(2) USING "region_code"::varchar(2);--> statement-breakpoint
ALTER TABLE "record_ranks"."persons" ALTER COLUMN "region_code" SET DATA TYPE varchar(2) USING "region_code"::varchar(2);--> statement-breakpoint
ALTER TABLE "record_ranks"."results" ALTER COLUMN "region_code" SET DATA TYPE varchar(2) USING "region_code"::varchar(2);--> statement-breakpoint
ALTER TABLE "record_ranks"."contests" ADD CONSTRAINT "contests_region_code_regions_code_fkey" FOREIGN KEY ("region_code") REFERENCES "record_ranks"."regions"("code") ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."persons" ADD CONSTRAINT "persons_region_code_regions_code_fkey" FOREIGN KEY ("region_code") REFERENCES "record_ranks"."regions"("code") ON UPDATE CASCADE;--> statement-breakpoint
ALTER TABLE "record_ranks"."results" ADD CONSTRAINT "results_region_code_regions_code_fkey" FOREIGN KEY ("region_code") REFERENCES "record_ranks"."regions"("code") ON UPDATE CASCADE;